#!/bin/sh /etc/rc.common
# welled init script
# Copyright (C) 2017 Carnegie Mellon University
 
START=91
STOP=92

NAME=welled
PROG=/bin/welled

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param pidfile /var/run/welled.pid
	procd_close_instance
}                 

